server:
  port: PORT
  sessionSecret: SESSION_SECRET
  lti:
    consumerKey: CONSUMER_KEY
    consumerSecret: CONSUMER_SECRET

client:
  dataServer:
    email: DATASERVER_EMAIL
    password: DATASERVER_PASSWORD
  firebase:
    __name: FIREBASE_CONFIG
    __format: json
